scss_files: "app/assets/stylesheets/**"
exclude:
  - "app/assets/stylesheets/application.css"
  - "vendor/assets/**"
linters:
  VendorPrefix:
    enabled: false
  PlaceholderInExtend:
    enabled: false
